version: "3.8"

services:
  chat_app_frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: chat_app_frontend
    hostname: chat_app_frontend
    # ports:
    #   - "5173:5173"
    networks:
      - nginx_chat_app_network
    depends_on:
      - chat_app_backend
  
  chat_app_backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: chat_app_backend
    hostname: chat_app_backend
    networks:
      - nginx_chat_app_network
  
  nginx_proxy:
    image: nginx:1.27.4
    container_name: nginx_proxy
    hostname: nginx_proxy
    ports:
      - "7000:7000"
      - "8000:8000"
    volumes:
      - "D:/Sz - projects/0-practice/devops/nginx/3-nginx-websocket-chat-app/nginx.dev.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - nginx_chat_app_network
    depends_on:
      - chat_app_frontend
      - chat_app_backend

networks:
  nginx_chat_app_network:
    driver: bridge