FROM node:20.16.0-alpine

RUN addgroup -S app && adduser -S -G app app

USER root

WORKDIR /usr/src/app

COPY --chown=app:app package*.json ./

RUN npm i

COPY --chown=app:app . ./

EXPOSE 5173

CMD ["npm", "run", "dev"]