FROM node:20.16.0-alpine AS builder_stage

RUN addgroup -S app && adduser -S -G app app

USER root

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install nodemon

USER app

COPY --chown=app:app . ./
# RUN chown -R app:app /usr/src/app

EXPOSE 4000

CMD [ "npm", "run", "dev" ]
