version: "3.8"

services:
  mouse_app_frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: mouse_app_frontend
    hostname: mouse_app_frontend
    # ports:
    #   - "5173:5173"
    networks:
      - nginx_mouse_app_network
    depends_on:
      - mouse_app_backend

  mouse_app_backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: mouse_app_backend
    hostname: mouse_app_backend
    # ports:
    #   - "9000:9000"
    networks:
      - nginx_mouse_app_network

  nginx_loadbalancer:
    image: nginx:1.27.4
    container_name: nginx_loadbalancer
    hostname: nginx_loadbalancer
    ports:
      - "7000:7000"
      - "8000:8000"
    networks:
      - nginx_mouse_app_network
    volumes:
      - "D:/Sz - projects/0-practice/devops/nginx/2-nginx-websocket-mouse-app/nginx.dev.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - mouse_app_frontend
      - mouse_app_backend

networks:
  nginx_mouse_app_network:
    driver: bridge