FROM node:24.2.0-alpine AS build_phase

RUN addgroup app && adduser -S -G app app

USER root

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# USER app

COPY --chown=app:app . ./

EXPOSE 5173

CMD ["npm", "run", "dev"]