FROM node:24.2.0-alpine3.22 AS builder_stage

RUN addgroup -S app && adduser -S -G app app

USER root

WORKDIR /usr/src/app

COPY --chown=app:app package*.json ./

RUN npm install

RUN npm install nodemon

COPY --chown=app:app . ./

USER app

EXPOSE 4000

CMD [ "npm", "run", "dev" ]
