version: "3.8"
services:
  nodeapp1:
    image: "249"
    container_name: nodeapp1
    hostname: nodeapp1
    networks:
      - nginx_network

  nodeapp2:
    image: "249"
    container_name: nodeapp2
    hostname: nodeapp2
    networks:
      - nginx_network

  nodeapp3:
    image: "249"
    container_name: nodeapp3
    hostname: nodeapp3
    networks:
      - nginx_network

  nginx_container:
    image: nginx:1.27.4
    container_name: nginx_container
    hostname: nginx_container
    networks:
      - nginx_network
    depends_on:
      - nodeapp1
      - nodeapp2
      - nodeapp3
    ports:
      - 80:80
      - 90:90
    volumes:
      - "D:/Sz - projects/0-practice/devops/nginx/1-simple-nginx-docker-nodeapp/nginx.conf:/etc/nginx/nginx.conf"
    restart: unless-stopped

networks:
  nginx_network:
    driver: bridge