FROM node:24.2.0-alpine

RUN addgroup -S app && adduser -S app -G app

USER root

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install nodemon

COPY --chown=app:app . ./

USER app

EXPOSE 4000

CMD [ "npm", "run", "dev" ]