version: "3.8"

services:
  mouse_app_frontend:
    build:
      context: ./client1
      dockerfile: Dockerfile.dev
    container_name: mouse_app_frontend
    hostname: mouse_app_frontend
    ports:
      - "5173:5173"
    networks:
      - nginx_websocket_network
    depends_on:
      - server1

  chat_app_frontend:
    build:
      context: ./client2
      dockerfile: Dockerfile.dev
    container_name: chat_app_frontend
    hostname: chat_app_frontend
    ports:
      - "5174:5173"
    networks:
      - nginx_websocket_network
    depends_on:
      - server2

  mouse_app_backend:
    build:
      context: ./server1
      dockerfile: Dockerfile.dev
    container_name: mouse_app_backend
    hostname: mouse_app_backend
    ports:
      - "9000:9000"
    networks:
      - nginx_websocket_network

  chat_app_backend:
    build:
      context: ./server2
      dockerfile: Dockerfile.dev
    container_name: chat_app_backend
    hostname: chat_app_backend
    ports:
      - "9001:9000"
    networks:
      - nginx_websocket_network

networks:
  nginx_websocket_network:
    driver: bridge