FROM node:20.16.0-alpine AS build_phase

RUN addgroup app && adduser -S -G app app

USER root

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN npm install nodemon

USER app

COPY --chown=app:app . .

EXPOSE 9000

CMD ["npm", "run", "dev"]